### ISSUE TITLE
Peer to peer review: Add link to logo to redirect to index.html

### ISSUE THREAD

**Issue by MissieKahsay** [Elhambasir/Awesome_books#4]
Hi @UbdaNam ,

Good job with completing the project and addressing all requirements. I will like to commend you for that.

The only issue I have is I noticed that when I click on the logo in the header, it doesn't take me back to the homepage. I think it would be great if the logo acted as a link to the homepage (i.e., index.html).

Can you please consider adding a link to the logo that will redirect to the index.html page when clicked? This would make it easier for users to navigate back to the homepage.

Thanks!

**Comment by UbdaNam** [comment]
@MussieTeka Thanks for reviewing our code 😀
